version: "3.7"

services:
  app:
    image: node:12-alpine
    command: npm run dev
    ports:
      - 4445:4445
    working_dir: /
    volumes:
      - ./:/app
    my-services:
      network_mode: host
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DB:
    mysql:
      image: mysql:5.7
      volumes:
        - todo-mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: todos
volumes:
  todo-mysql-data: